### ISSUE TITLE
Skyott cookie app

### ISSUE THREAD

**Issue by gmjh123** [Paco8/plugin.video.skyott#60] opened 2024-11-17 16:31 UTC
Hi, I've used this in the past and it worked fine. But now it doesn't seem to generate any key file. Or if it does, I don't know where it is. When entering my details on the skyott cookie add-on it redirects me to a page saying oops something went wrong and there is no Chrome page to close. The instructions you have for this say "the token will be saved in the same folder as a key file." 

The same folder as what? I don't know where the key file is. Thanks very much

**Comment by Paco8** [comment] 2024-11-17 23:28
The key file is saved in the same folder where the application is. 
You can also try the android version, I've just tested it and it works:
https://github.com/Paco8/SkyExtractCookieAndroid

**Comment by gmjh123** [comment] 2024-11-17 23:41
Thanks for the reply. I'm already using the Android version. There is no key file saved in the same folder as the app. I think the problem is that when I sign in to peacock it doesn't open a Chrome page it just opens a page saying "this browser is unsupported" inside the sky cookie app itself I've used this cookie app before in the past, but it isn't saving anything in the same folder anymore.

**Comment by gmjh123** [comment] 2024-11-18 01:19
> The key file is saved in the same folder where the application is. You can also try the android version, I've just tested it and it works: https://github.com/Paco8/SkyExtractCookieAndroid

I've just tried it again with the link that you gave hoping that there might be some updated element to it. It's exactly the same, it just gives a page saying this is an unsupported browser and no key file is generated

**Comment by gmjh123** [comment] 2024-11-18 05:22
> I tested it with skyshowtime. I guess peacock changed something. I'll look into it.

Okay thanks. I think I got the message of "this browser is not supported" when it was working previously and produced the key file. So I don't think that's got anything to do with why it's now failing.

**Comment by Paco8** [comment] 2024-11-20 12:52
I think the problem is fixed in the latest version:
https://github.com/Paco8/SkyExtractCookieAndroid/releases/tag/v1.0.2

**Comment by gmjh123** [comment] 2024-11-20 15:00
Yes it's working now, thanks very much

**Closed** 2024-11-20 15:00 UTC
