### ISSUE TITLE
Allows for separate Dolby Vision and HDR10 settings in UHD

### ISSUE THREAD

**Issue by Liqianyu** [Paco8/plugin.video.skyott#28] opened 2023-06-20 16:48 UTC
In the latest add-on version (v0.4.3), Dolby Vision and HDR10 support are enabled by default if UHD is enabled. This is incorrect, as not all 4K TVs support Dolby Vision, and some do not even support HDR10.

So it should be allowed to enable HDR10\Dolby Vision in UHD separate setting.

**Comment by Paco8** [comment] 2023-06-25 14:05
Let me know if the issue is fixed in this package:
[plugin.video.skyott-0.4.3-2.zip](https://github.com/Paco8/plugin.video.skyott/files/11859894/plugin.video.skyott-0.4.3-2.zip)

**Closed** 2023-06-28 13:07 UTC
